### ISSUE TITLE
polling or sockets?

### ISSUE THREAD

**Issue by Marak** [Marak/zztmmo#2]
we are going to require a seamless real-time experience.

its to my understanding that zzt is tick based, meaning we are rendering at set intervals on the screen. if we miss an update we are going to lose a tick...which means each update we lose stacks up the lag and people will warp :-(

regardless, we will need to make a decision as to what we will be using a websocket / xhr library. i don't think we should roll our own, but we might have to customize whatever we start with. any suggestions?

if we have to use websockets i think thats OK. we will utilize SWF fallback for legacy browsers. let me know what you think.

**Comment by nefD** [comment]
I'm personally inclined to recommend the web socket w/ flash fall back option. It'd make the back end development significantly easier. Wouldn't the overall network overhead be greater with an xhr option, due to the need for connection establishment and the sending of headers each time a poll fires?

**Comment by Marak** [comment]
socket.io bitches!
